import React, { useEffect, useState } from "react";
import logo from "../brand/ussignal.png";
import "./governed-operational-read-center.css";

const format = value => typeof value === "boolean" ? (value ? "Yes" : "No") : String(value ?? "Not recorded");
export default function GovernedOperationalReadCenter({ module, title, subtitle, basePath, surfaces }) {
  const [data,setData]=useState({}); const [errors,setErrors]=useState({}); const [loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;Promise.allSettled(surfaces.map(async key=>{const response=await fetch(`${basePath}/${key}`,{credentials:"include"});const body=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(body.message||`Unable to load ${key}.`),{key});return[key,body];})).then(results=>{if(!active)return;const rows={},failures={};results.forEach((result,index)=>{const key=surfaces[index];if(result.status==="fulfilled")rows[key]=result.value[1];else failures[key]=result.reason?.message||`Unable to load ${key}.`;});setData(rows);setErrors(failures);setLoading(false);});return()=>{active=false};},[basePath,surfaces]);
  return <section className="governed-operations-center" data-module={module}><header className="governed-operations-hero"><img src={logo} alt="US Signal"/><div><span>ProjectPulse · Module {module}</span><h1>{title}</h1><p>{subtitle}</p></div></header><aside><strong>Governed operation:</strong> Read and planning capabilities are available. External or high-impact execution remains approval-controlled.</aside>{loading&&<p role="status">Loading operational information…</p>}<main>{surfaces.map(key=>{const surface=data[key],error=errors[key];return <article key={key}><div className="governed-operations-heading"><div><small>{key.replaceAll("-"," ")}</small><h2>{surface?.title||key.replaceAll("-"," ")}</h2></div><span className={error?"is-error":"is-ready"}>{error?"Unavailable":surface?.liveData?"Ready":"Not configured"}</span></div>{error?<p role="alert">{error}</p>:<><p>{surface?.description}</p><div className="governed-operations-entries">{surface?.entries?.length?surface.entries.map((entry,index)=><dl key={index}>{Object.entries(entry).map(([name,value])=><div key={name}><dt>{name.replaceAll("_"," ")}</dt><dd>{format(value)}</dd></div>)}</dl>):<p>No records yet. Use the next action when configuration authority is enabled.</p>}</div><button type="button" disabled title="Enabled in the operational activation phase">{surface?.action||"Configure"}</button></>}</article>})}</main></section>;
}
