import { useCallback, useEffect, useMemo, useState } from 'react';
import { usSignalLogoDataUrl } from './assets/usSignalLogoData.js';
import './oem-vendor-directory-center.css';

function token(authSession){return authSession?.sessionToken??authSession?.token??authSession?.accessToken??window.localStorage.getItem('projectPulseSessionToken')??window.sessionStorage.getItem('projectPulseSessionToken')??''}
function authHeaders(authSession,extra={}){const value=token(authSession);return{...(value?{Authorization:`Bearer ${value}`,'X-ProjectPulse-Session':value,'X-Project-Pulse-Session':value,'X-Session-Token':value}:{}),...extra}}
async function requestJson(path,authSession,options={}){const response=await fetch(path,{credentials:'include',...options,headers:authHeaders(authSession,options.headers)});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.message??`Module 074 returned HTTP ${response.status}.`);return payload}
const blank=()=>({id:crypto.randomUUID(),vendorName:'',oemCategory:'',status:'active',website:'',contactsText:'',linksText:'',certificationsText:'',productsText:'',notes:''});
const lines=value=>String(value??'').split(/\r?\n/).map(item=>item.trim()).filter(Boolean);
function payload(vendor){return{id:vendor.id,vendorName:vendor.vendorName,oemCategory:vendor.oemCategory,status:vendor.status,website:vendor.website,contacts:lines(vendor.contactsText).map(line=>{const[name='',role='',email='',phone='']=line.split('|').map(value=>value.trim());return{name,role,email,phone}}),supportLinks:lines(vendor.linksText).map(line=>{const[label='',url='']=line.split('|').map(value=>value.trim());return{label,url}}),certifications:String(vendor.certificationsText??'').split(',').map(value=>value.trim()).filter(Boolean).map(certificationName=>({certificationName})),products:String(vendor.productsText??'').split(',').map(value=>value.trim()).filter(Boolean).map(productName=>({productName})),notes:vendor.notes}}
function saveFile(name,type,content){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}

export default function OemVendorDirectoryCenter({authSession}){
 const [tab,setTab]=useState('directory');const[search,setSearch]=useState('');const[state,setState]=useState({loading:true,validating:false,capabilities:null,reference:{statuses:[],suggestedCategories:[]},vendors:[],validation:null,error:'',notice:''});
 const canManage=state.capabilities?.access?.canManage===true;const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?state.vendors.filter(vendor=>[vendor.vendorName,vendor.oemCategory,vendor.status,vendor.productsText].some(value=>String(value??'').toLowerCase().includes(q))):state.vendors},[search,state.vendors]);
 const load=useCallback(async()=>{setState(current=>({...current,loading:true,error:'',notice:''}));try{const[capabilities,directory,reference]=await Promise.all([requestJson('/api/oem-vendor-directory/capabilities',authSession),requestJson('/api/oem-vendor-directory/directory',authSession),requestJson('/api/oem-vendor-directory/reference',authSession)]);setState(current=>({...current,loading:false,capabilities,reference,vendors:current.vendors.length?current.vendors:(directory.vendors??[]),error:'',notice:directory.message??''}))}catch(error){setState(current=>({...current,loading:false,error:error?.message??'Vendor directory is unavailable.'}))}},[authSession]);useEffect(()=>{void load()},[load]);
 const update=(id,field,value)=>setState(current=>({...current,vendors:current.vendors.map(vendor=>vendor.id===id?{...vendor,[field]:value}:vendor),validation:null,notice:''}));const remove=id=>setState(current=>({...current,vendors:current.vendors.filter(vendor=>vendor.id!==id),validation:null,notice:'Vendor removed from the unsaved draft.'}));
 const validate=async()=>{setState(current=>({...current,validating:true,error:'',notice:''}));try{const result=await requestJson('/api/oem-vendor-directory/validate',authSession,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({vendors:state.vendors.map(payload)})});setState(current=>({...current,validating:false,validation:result,notice:result.valid?'Vendor draft passed validation.':'Vendor draft contains validation errors.'}))}catch(error){setState(current=>({...current,validating:false,error:error?.message??'Vendor validation failed.'}))}};
 const exportJson=()=>saveFile('oem-vendor-directory-draft.json','application/json',JSON.stringify({version:1,vendors:state.vendors.map(payload)},null,2));const exportCsv=()=>{const columns=[['vendor_name','vendorName'],['oem_category','oemCategory'],['status','status'],['website','website'],['products','productsText'],['certifications','certificationsText'],['notes','notes']];const quote=value=>`"${String(value??'').replace(/"/g,'""')}"`;saveFile('oem-vendor-directory-summary.csv','text/csv;charset=utf-8',[columns.map(([name])=>name).join(','),...state.vendors.map(vendor=>columns.map(([,field])=>quote(vendor[field])).join(','))].join('\n'))};
 return <section className="panel vendor-directory-center" data-module="074" data-persistence="unsaved-draft" aria-labelledby="vendor-directory-title">
  <header className="vendor-directory-hero"><div className="vendor-directory-lockup"><img src={usSignalLogoDataUrl} alt="US Signal"/><div><p>Module 074 · Delivery ecosystem</p><h1 id="vendor-directory-title">OEM & Vendor Directory</h1><span>Contacts, support paths, certifications, products, and delivery status in one governed catalog.</span></div></div><div className="vendor-directory-authority"><strong>{canManage?'Draft editor':'Read-only viewer'}</strong><small>{canManage?'Admin · Solution Architect · PTC':'All authenticated users can view'}</small></div></header><div className="vendor-directory-stripe" aria-hidden="true"><i/><i/><i/></div>
  {state.error?<div className="vendor-directory-banner error" role="alert">{state.error}</div>:null}{state.notice?<div className="vendor-directory-banner notice" role="status">{state.notice}</div>:null}<div className="vendor-directory-banner governed">No canonical persistence source is authorized. Editing, validation, and export operate on an unsaved draft only.</div>
  <nav className="vendor-directory-tabs">{[['directory','Vendor directory'],['instructions','Field guide'],['governance','Governance']].map(([value,label])=><button type="button" key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{label}</button>)}</nav>
  {tab==='directory'?<section className="vendor-directory-card"><div className="vendor-directory-card-head"><div><p>SAL-003 canonical draft</p><h2>Supported vendors</h2></div><div className="vendor-directory-actions"><button type="button" onClick={exportCsv}>Export CSV</button><button type="button" onClick={exportJson}>Export JSON</button>{canManage?<button type="button" onClick={()=>setState(current=>({...current,vendors:[...current.vendors,blank()]}))}>Add vendor</button>:null}{canManage?<button type="button" className="primary" onClick={validate} disabled={state.validating||!state.vendors.length}>Validate draft</button>:null}</div></div>
   <label className="vendor-directory-search"><span>Search name, category, status, or product</span><input type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search vendors…"/></label>
   <div className="vendor-directory-grid">{filtered.map(vendor=><article key={vendor.id} className="vendor-directory-vendor"><header><div><span>{vendor.oemCategory||'Uncategorized'}</span><h3>{vendor.vendorName||'New vendor'}</h3></div><b className={vendor.status}>{vendor.status.replace(/_/g,' ')}</b></header>{canManage?<div className="vendor-directory-form">
    <label><span>Vendor name</span><input value={vendor.vendorName} onChange={e=>update(vendor.id,'vendorName',e.target.value)}/></label><label><span>OEM category</span><input list="vendor-categories" value={vendor.oemCategory} onChange={e=>update(vendor.id,'oemCategory',e.target.value)}/></label><label><span>Status</span><select value={vendor.status} onChange={e=>update(vendor.id,'status',e.target.value)}>{(state.reference.statuses??['active']).map(value=><option key={value} value={value}>{value.replace(/_/g,' ')}</option>)}</select></label><label><span>Website (HTTPS)</span><input type="url" value={vendor.website} onChange={e=>update(vendor.id,'website',e.target.value)}/></label>
    <label className="wide"><span>Contacts — one per line: Name | Role | Email | Phone</span><textarea rows="3" value={vendor.contactsText} onChange={e=>update(vendor.id,'contactsText',e.target.value)}/></label><label className="wide"><span>Support links — one per line: Label | HTTPS URL</span><textarea rows="3" value={vendor.linksText} onChange={e=>update(vendor.id,'linksText',e.target.value)}/></label><label><span>Certifications (comma separated)</span><textarea rows="2" value={vendor.certificationsText} onChange={e=>update(vendor.id,'certificationsText',e.target.value)}/></label><label><span>Products (comma separated)</span><textarea rows="2" value={vendor.productsText} onChange={e=>update(vendor.id,'productsText',e.target.value)}/></label><label className="wide"><span>Delivery notes</span><textarea rows="2" value={vendor.notes} onChange={e=>update(vendor.id,'notes',e.target.value)}/></label><button type="button" className="danger" onClick={()=>remove(vendor.id)}>Remove vendor</button>
   </div>:<div className="vendor-directory-view"><p>{vendor.notes||'No delivery notes.'}</p><span>{vendor.productsText||'No products recorded.'}</span><span>{vendor.certificationsText||'No certifications recorded.'}</span></div>}</article>)}{!state.loading&&!filtered.length?<div className="vendor-directory-empty">No vendor records match this view. Authorized editors can build a source-only draft.</div>:null}</div>
   <datalist id="vendor-categories">{(state.reference.suggestedCategories??[]).map(value=><option key={value} value={value}/>)}</datalist>{state.validation?<div className={`vendor-directory-validation ${state.validation.valid?'valid':'invalid'}`}><strong>{state.validation.valid?'Draft valid':'Draft needs attention'}</strong><span>{state.validation.validCount} valid · {state.validation.errorCount} errors</span>{(state.validation.errors??[]).map((error,index)=><code key={`${error.vendorRow}-${error.itemRow}-${error.code}-${index}`}>Vendor {error.vendorRow}{error.itemRow?`, item ${error.itemRow}`:''}: {error.code}</code>)}</div>:null}
  </section>:null}
  {tab==='instructions'?<section className="vendor-directory-card vendor-directory-guide"><h2>Canonical field guide</h2><div><article><strong>Contacts</strong><p>Named vendor/OEM contacts with role, email, and phone. Email is validated when present.</p></article><article><strong>Support links</strong><p>Labelled HTTPS-only support, portal, documentation, or escalation links.</p></article><article><strong>Certifications</strong><p>Vendor program or delivery certifications relevant to US Signal services.</p></article><article><strong>Products</strong><p>Supported product families or offerings used for delivery context.</p></article></div></section>:null}
  {tab==='governance'?<section className="vendor-directory-card vendor-directory-governance"><h2>SAL-003 governed boundary</h2><p>All authenticated users may view. Administrators, Super Administrators, Solution Architects, and Project Team Coordinators may edit and validate drafts. Database persistence, audit history, imports, external synchronization, and public APIs require separate decisions.</p><ul><li>Vendor names must be unique.</li><li>Support links must use HTTPS.</li><li>Status uses a controlled vocabulary.</li><li>No vendor list was invented or copied into source.</li></ul></section>:null}
  <footer className="vendor-directory-footer"><img src={usSignalLogoDataUrl} alt="" aria-hidden="true"/><span>US Signal · Trusted delivery ecosystem</span><small>Module 074 · Source-only candidate</small></footer>
 </section>
}
