import { useCallback, useEffect, useMemo, useState } from 'react';
import { usSignalLogoDataUrl } from './assets/usSignalLogoData.js';
import './sales-coverage-alignment-center.css';
import './projectpulse-module-standard.css';

function token(authSession){return authSession?.sessionToken??authSession?.token??authSession?.accessToken??window.localStorage.getItem('projectPulseSessionToken')??window.sessionStorage.getItem('projectPulseSessionToken')??''}
function headers(authSession,extra={}){const value=token(authSession);return {...(value?{Authorization:`Bearer ${value}`,'X-ProjectPulse-Session':value,'X-Project-Pulse-Session':value,'X-Session-Token':value}:{}),...extra}}
async function requestJson(path,authSession,options={}){const response=await fetch(path,{credentials:'include',...options,headers:headers(authSession,options.headers)});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.message??`Module 073 returned HTTP ${response.status}.`);return payload}
const today=()=>new Date().toISOString().slice(0,10);
const blank=()=>({id:crypto.randomUUID(),accountExecutiveUserId:'',primaryResaleOperationsUserId:'',backupResaleOperationsUserId:'',solutionArchitectUserId:'',territory:'',team:'',effectiveStartDate:today(),effectiveEndDate:'',notes:''});
function download(rows){const columns=[['account_executive_user_id','accountExecutiveUserId'],['primary_resale_operations_user_id','primaryResaleOperationsUserId'],['backup_resale_operations_user_id','backupResaleOperationsUserId'],['solution_architect_user_id','solutionArchitectUserId'],['territory','territory'],['team','team'],['effective_start_date','effectiveStartDate'],['effective_end_date','effectiveEndDate'],['notes','notes']];const quote=(value)=>`"${String(value??'').replace(/"/g,'""')}"`;const content=[columns.map(([name])=>name).join(','),...rows.map(row=>columns.map(([,field])=>quote(row[field])).join(','))].join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='sales-coverage-alignment-draft.csv';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}

export default function SalesCoverageAlignmentCenter({authSession}){
  const [tab,setTab]=useState('alignment');
  const [state,setState]=useState({loading:true,validating:false,capabilities:null,signals:[],identities:[],rows:[],validation:null,error:'',notice:''});
  const canManage=state.capabilities?.access?.canManage===true;
  const byCategory=useMemo(()=>{const result={account_executive:[],resale_operations:[],solution_architect:[]};state.identities.forEach(identity=>(identity.categories??[]).forEach(category=>result[category]?.push(identity)));return result},[state.identities]);
  const identityName=useCallback((id)=>state.identities.find(item=>item.userId===id)?.displayName??'Unassigned',[state.identities]);
  const load=useCallback(async()=>{setState(current=>({...current,loading:true,error:'',notice:''}));try{const capabilities=await requestJson('/api/sales-coverage/capabilities',authSession);const [signals,identityPayload]=await Promise.all([requestJson('/api/sales-coverage/source-signals',authSession),capabilities.access?.canManage?requestJson('/api/sales-coverage/identity-options',authSession):Promise.resolve({identities:[]})]);setState(current=>({...current,loading:false,capabilities,signals:[...(signals.projects??[]),...(signals.intake??[])],identities:identityPayload.identities??[],error:''}))}catch(error){setState(current=>({...current,loading:false,error:error?.message??'Sales coverage is unavailable.'}))}},[authSession]);
  useEffect(()=>{void load()},[load]);
  const update=(id,field,value)=>setState(current=>({...current,rows:current.rows.map(row=>row.id===id?{...row,[field]:value}:row),validation:null,notice:''}));
  const remove=(id)=>setState(current=>({...current,rows:current.rows.filter(row=>row.id!==id),validation:null,notice:'Draft row removed.'}));
  const fromSignals=()=>setState(current=>({...current,rows:current.signals.map(signal=>({...blank(),accountExecutiveUserId:signal.accountExecutiveUserId??'',solutionArchitectUserId:signal.solutionArchitectUserId??'',effectiveStartDate:signal.effectiveStartDate??today(),effectiveEndDate:signal.effectiveEndDate??'',notes:`${signal.sourceType}: ${signal.sourceCode} · ${signal.customerName}`})),validation:null,notice:'Source signals copied into an unsaved alignment draft.'}));
  const validate=async()=>{setState(current=>({...current,validating:true,error:'',notice:''}));try{const payload=await requestJson('/api/sales-coverage/validate',authSession,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({alignments:state.rows})});setState(current=>({...current,validating:false,validation:payload,notice:payload.valid?'Draft passed structural validation.':'Draft contains validation errors.'}))}catch(error){setState(current=>({...current,validating:false,error:error?.message??'Draft validation failed.'}))}};
  const options=(category)=><>{byCategory[category].map(identity=><option key={identity.userId} value={identity.userId}>{identity.displayName} · {identity.team||identity.jobTitle}</option>)}</>;
  return <section className="panel sales-coverage-center projectpulse-module-standard" data-module="073"
      data-brand="us-signal" data-persistence="unsaved-draft" aria-labelledby="sales-coverage-title">
    <header className="sales-coverage-hero"><div className="sales-coverage-lockup"><img src={usSignalLogoDataUrl} alt="US Signal"/><div><p>Module 073 · Sales and delivery alignment</p><h1 id="sales-coverage-title">Sales Coverage Alignment</h1><span>Effective-dated AE, Resale Operations, and Solution Architect responsibility mapping.</span></div></div><div className="sales-coverage-authority"><strong>{canManage?'Draft editor':'Read-only viewer'}</strong><small>{canManage?'Admin · Solution Architect · PTC':'All authenticated users can view'}</small></div></header>
    <div className="sales-coverage-stripe" aria-hidden="true"><i/><i/><i/></div>
    {state.error?<div className="sales-coverage-banner error" role="alert">{state.error}</div>:null}{state.notice?<div className="sales-coverage-banner success" role="status">{state.notice}</div>:null}
    <div className="sales-coverage-banner governed">Edits remain an unsaved, validated draft until an effective-dated persistence model and database change are authorized.</div>
    <nav className="sales-coverage-tabs">{[['alignment','Alignment draft'],['signals','Current signals'],['governance','Governance']].map(([value,label])=><button type="button" key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{label}</button>)}</nav>
    {tab==='alignment'?<section className="sales-coverage-card"><div className="sales-coverage-card-head"><div><p>Identity-backed working copy</p><h2>Coverage relationships</h2></div><div className="sales-coverage-actions"><button type="button" onClick={()=>download(state.rows)}>Export draft</button>{canManage?<button type="button" onClick={fromSignals}>Start from signals</button>:null}{canManage?<button type="button" onClick={()=>setState(current=>({...current,rows:[...current.rows,blank()]}))}>Add relationship</button>:null}{canManage?<button type="button" className="primary" onClick={validate} disabled={state.validating||!state.rows.length}>Validate draft</button>:null}</div></div>
      <div className="sales-coverage-table"><table><thead><tr><th>Account Executive</th><th>Primary Resale Ops</th><th>Backup Resale Ops</th><th>Solution Architect</th><th>Territory / team</th><th>Effective dates</th>{canManage?<th>Action</th>:null}</tr></thead><tbody>{state.rows.map(row=><tr key={row.id}>
        <td>{canManage?<select value={row.accountExecutiveUserId} onChange={e=>update(row.id,'accountExecutiveUserId',e.target.value)}><option value="">Select AE…</option>{options('account_executive')}</select>:identityName(row.accountExecutiveUserId)}</td>
        <td>{canManage?<select value={row.primaryResaleOperationsUserId} onChange={e=>update(row.id,'primaryResaleOperationsUserId',e.target.value)}><option value="">Select primary…</option>{options('resale_operations')}</select>:identityName(row.primaryResaleOperationsUserId)}</td>
        <td>{canManage?<select value={row.backupResaleOperationsUserId} onChange={e=>update(row.id,'backupResaleOperationsUserId',e.target.value)}><option value="">No backup</option>{options('resale_operations')}</select>:identityName(row.backupResaleOperationsUserId)}</td>
        <td>{canManage?<select value={row.solutionArchitectUserId} onChange={e=>update(row.id,'solutionArchitectUserId',e.target.value)}><option value="">Select SA…</option>{options('solution_architect')}</select>:identityName(row.solutionArchitectUserId)}</td>
        <td><div className="sales-coverage-stack">{canManage?<><input value={row.territory} onChange={e=>update(row.id,'territory',e.target.value)} placeholder="Territory"/><input value={row.team} onChange={e=>update(row.id,'team',e.target.value)} placeholder="Team"/></>:<>{row.territory}<small>{row.team}</small></>}</div></td>
        <td><div className="sales-coverage-stack">{canManage?<><input type="date" value={row.effectiveStartDate} onChange={e=>update(row.id,'effectiveStartDate',e.target.value)}/><input type="date" value={row.effectiveEndDate} onChange={e=>update(row.id,'effectiveEndDate',e.target.value)}/></>:<>{row.effectiveStartDate}<small>{row.effectiveEndDate||'Open ended'}</small></>}</div></td>
        {canManage?<td><button type="button" className="danger" onClick={()=>remove(row.id)}>Remove</button></td>:null}</tr>)}{!state.rows.length?<tr><td colSpan={canManage?7:6} className="empty">No alignment draft rows. Current project/intake signals remain available in the next tab.</td></tr>:null}</tbody></table></div>
      {state.validation?<div className={`sales-coverage-validation ${state.validation.valid?'valid':'invalid'}`}><strong>{state.validation.valid?'Draft valid':'Draft needs attention'}</strong><span>{state.validation.validCount} valid · {state.validation.errorCount} errors</span>{(state.validation.errors??[]).map(error=><code key={`${error.row}-${error.code}`}>Row {error.row}: {error.code}</code>)}</div>:null}
    </section>:null}
    {tab==='signals'?<section className="sales-coverage-card"><div className="sales-coverage-card-head"><div><p>Existing ProjectPulse relationships</p><h2>Project and intake source signals</h2></div><button type="button" onClick={load}>Refresh</button></div><div className="sales-coverage-signal-grid">{state.signals.map(signal=><article key={`${signal.sourceType}-${signal.sourceId}`}><span>{signal.sourceType} · {signal.sourceCode}</span><h3>{signal.customerName}</h3><p>{signal.sourceName}</p><dl><div><dt>AE</dt><dd>{signal.accountExecutiveName||'Unassigned'}</dd></div><div><dt>SA</dt><dd>{signal.solutionArchitectName||'Unassigned'}</dd></div></dl></article>)}{!state.loading&&!state.signals.length?<div className="empty">No AE/SA source signals are present.</div>:null}</div></section>:null}
    {tab==='governance'?<section className="sales-coverage-card sales-coverage-governance"><h2>SAL-002 governed boundary</h2><p>All authenticated users may view. Administrators, Super Administrators, Solution Architects, and Project Team Coordinators may edit and validate local drafts. No draft is saved until an audited effective-dated data model is separately authorized.</p><ul><li>Stable identity IDs, never free-text people.</li><li>Primary and backup Resale Operations must differ.</li><li>Effective end cannot precede start.</li><li>Source signals remain visible and are not overwritten.</li></ul></section>:null}
    <footer className="sales-coverage-footer"><img src={usSignalLogoDataUrl} alt="" aria-hidden="true"/><span>US Signal · Connected sales-to-delivery ownership</span><small>Module 073 · Source-only candidate</small></footer>
  </section>
}
