using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;

namespace ProjectTime.Api.Modules;

/// <summary>
/// Delivers a bounded notification envelope to a centrally owned Power Automate HTTP-trigger flow.
/// The existing Module 065 services application provides the Entra identity. No custom Teams app,
/// per-user installation, webhook secret in source, or browser-held credential is required.
/// </summary>
internal static class MicrosoftTeamsWorkflowProtocol
{
    internal sealed record Evidence(string Code, string Message, string? RequestId = null);
    internal sealed record Outcome(string Status, Evidence Diagnostic, string? WorkflowRunId = null);

    internal sealed record Envelope(
        string EventId,
        string DestinationType,
        string[] Recipients,
        string? ConversationId,
        string? TeamId,
        string? ChannelId,
        string Subject,
        string Message,
        string Severity,
        string NotificationType,
        string SourceModule,
        string PulseUrl,
        string IdempotencyKey);

    internal static bool ValidTriggerUrl(string? value, out Uri? uri)
    {
        uri = null;
        if (string.IsNullOrWhiteSpace(value) || value.Length > 2048 || !Uri.TryCreate(value.Trim(), UriKind.Absolute, out var parsed)
            || parsed.Scheme != Uri.UriSchemeHttps || parsed.UserInfo.Length > 0) return false;
        var host = parsed.Host.ToLowerInvariant();
        if (!(host.EndsWith(".api.powerplatform.com", StringComparison.Ordinal)
              || host.EndsWith(".logic.azure.com", StringComparison.Ordinal))) return false;
        uri = parsed;
        return true;
    }

    internal static async Task<Outcome> ExecuteAsync(
        HttpClient client,
        Guid tenantId,
        Guid clientId,
        string clientSecret,
        string audience,
        string triggerUrl,
        Envelope envelope,
        CancellationToken cancellationToken)
    {
        if (tenantId == Guid.Empty || clientId == Guid.Empty || string.IsNullOrWhiteSpace(clientSecret))
            return Failed("teams_workflow_services_configuration_incomplete", "Save the matching Module 065 Microsoft services connection first.");
        if (!ValidTriggerUrl(triggerUrl, out var endpoint))
            return Failed("teams_workflow_url_invalid", "Save the HTTPS trigger URL generated by the centrally managed Power Automate flow.");
        if (string.IsNullOrWhiteSpace(audience)) audience = "https://service.flow.microsoft.com/";
        if (!Uri.TryCreate(audience, UriKind.Absolute, out var audienceUri) || audienceUri.Scheme != Uri.UriSchemeHttps)
            return Failed("teams_workflow_audience_invalid", "The Power Automate OAuth audience is invalid.");
        if (envelope.Recipients.Length == 0 || envelope.Recipients.Length > 100)
            return Failed("teams_workflow_recipient_count_invalid", "The workflow request must contain between 1 and 100 authorized recipients.");

        using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        timeout.CancelAfter(TimeSpan.FromSeconds(30));
        var ct = timeout.Token;
        var scope = audience.TrimEnd('/') + "/.default";
        using var tokenRequest = new HttpRequestMessage(HttpMethod.Post,
            $"https://login.microsoftonline.com/{tenantId:D}/oauth2/v2.0/token")
        {
            Content = new FormUrlEncodedContent(new Dictionary<string, string>
            {
                ["client_id"] = clientId.ToString("D"),
                ["client_secret"] = clientSecret,
                ["scope"] = scope,
                ["grant_type"] = "client_credentials"
            })
        };
        using var tokenResponse = await client.SendAsync(tokenRequest, HttpCompletionOption.ResponseHeadersRead, ct);
        if (tokenResponse.StatusCode != HttpStatusCode.OK)
            return Failed("teams_workflow_token_failed", "The centralized Microsoft services application could not obtain a Power Automate token.");

        using var tokenJson = await JsonDocument.ParseAsync(await tokenResponse.Content.ReadAsStreamAsync(ct), cancellationToken: ct);
        var token = tokenJson.RootElement.TryGetProperty("access_token", out var accessToken) ? accessToken.GetString() : null;
        if (string.IsNullOrWhiteSpace(token) || token.Length > 16384)
            return Failed("teams_workflow_token_missing", "Microsoft did not return a usable Power Automate token.");

        using var request = new HttpRequestMessage(HttpMethod.Post, endpoint);
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        request.Headers.Add("x-pulse-event-id", envelope.EventId);
        request.Headers.Add("x-pulse-idempotency-key", envelope.IdempotencyKey);
        request.Content = JsonContent.Create(envelope);
        using var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);

        var requestId = Header(response, "x-ms-request-id") ?? Header(response, "request-id") ?? Header(response, "client-request-id");
        var runId = Header(response, "x-ms-workflow-run-id");
        if ((int)response.StatusCode is >= 200 and < 300)
            return new("sent", new("teams_workflow_accepted", "Power Automate accepted the Teams delivery request. The workflow run remains the delivery authority.", requestId), runId);

        if (response.StatusCode == HttpStatusCode.TooManyRequests)
            return new("failed", new("teams_workflow_rate_limited", "Power Automate rate-limited this request. Preserve the event for a deliberate later retry.", requestId));
        if (response.StatusCode is HttpStatusCode.Unauthorized or HttpStatusCode.Forbidden)
            return new("failed", new("teams_workflow_not_authorized", "Power Automate rejected the centralized services identity. Verify the flow trigger allows this service principal.", requestId));
        return new((int)response.StatusCode >= 500 ? "outcome_unknown" : "failed",
            new($"teams_workflow_http_{(int)response.StatusCode}", "Power Automate did not confirm Teams delivery. Review the workflow run and request identifier before retrying.", requestId), runId);
    }

    private static Outcome Failed(string code, string message) => new("failed", new(code, message));
    private static string? Header(HttpResponseMessage response, string name)
        => response.Headers.TryGetValues(name, out var values) ? values.FirstOrDefault() : null;
}
