using Npgsql;

namespace ProjectTime.Api.Modules;

/// <summary>
/// Provides one authoritative, all-date approval backlog for the dashboard and
/// role-specific bulk completion for Manager, Project Manager, and PTC-final stages.
/// Approval comments are generated by the server so users do not have to enter a
/// comment for an approval. Return/rejection actions remain in the existing role
/// workspaces and continue to require a reason.
/// </summary>
public static partial class PendingApprovalWorkModule
{
    private static readonly HashSet<string> OrganizationApprovalRoles = new(StringComparer.OrdinalIgnoreCase)
    {
        "SUPER_ADMINISTRATOR",
        "ADMINISTRATOR",
        "PROJECT_TEAM_COORDINATOR"
    };

    private static readonly HashSet<string> ManagerApprovalRoles = new(StringComparer.OrdinalIgnoreCase)
    {
        "MANAGER",
        "PEOPLE_MANAGER",
        "ENGINEERING_LEAD",
        "ENGINEERING_TEAM_LEAD"
    };

    private static readonly HashSet<string> ProjectApprovalRoles = new(StringComparer.OrdinalIgnoreCase)
    {
        "PROJECT_MANAGER",
        "PROJECT_MANAGEMENT",
        "PROJECT_MANAGEMENT_LEAD",
        "PROJECT_MANAGEMENT_TEAM_LEAD",
        "PM_TEAM_LEAD"
    };

    public static WebApplication MapPendingApprovalWorkEndpoints(this WebApplication app)
    {
        app.MapGet("/api/approval-work/pending", GetPendingApprovalWorkAsync);
        app.MapPost("/api/approval-work/bulk-complete", BulkCompleteApprovalWorkAsync);
        return app;
    }

    private static async Task<IResult> GetPendingApprovalWorkAsync(HttpContext context)
    {
        await using var connection = new NpgsqlConnection(ConnectionString());
        await connection.OpenAsync(context.RequestAborted);

        var access = await LoadAccessAsync(connection, context, context.RequestAborted);
        if (access is null)
        {
            return Results.Json(new
            {
                status = "session_required",
                message = "A valid Pulse session is required."
            }, statusCode: StatusCodes.Status401Unauthorized);
        }

        if (!access.CanViewAnyApprovalWork)
        {
            return Results.Json(new
            {
                status = "access_denied",
                message = "No approval work is assigned to the current role."
            }, statusCode: StatusCodes.Status403Forbidden);
        }

        var items = await LoadPendingItemsAsync(
            connection,
            transaction: null,
            access,
            stage: null,
            weekStart: null,
            context.RequestAborted);

        var managerCount = items.Count(item => item.Stage == "manager");
        var projectManagerCount = items.Count(item => item.Stage == "pm");
        var ptcFinalCount = items.Count(item => item.Stage == "ptc");

        var pendingWeeks = items
            .GroupBy(item => new { item.Stage, item.StageLabel, item.WeekStart, item.WeekEnd })
            .Select(group => new
            {
                group.Key.Stage,
                group.Key.StageLabel,
                group.Key.WeekStart,
                group.Key.WeekEnd,
                count = group.Count(),
                totalHours = decimal.Round(group.Sum(item => item.TotalHours), 2),
                oldestPendingAt = group.Min(item => item.PendingAt),
                newestPendingAt = group.Max(item => item.PendingAt)
            })
            .OrderBy(group => group.WeekStart)
            .ThenBy(group => StageOrder(group.Stage))
            .ToArray();

        return Results.Ok(new
        {
            status = "pending_approval_work_loaded",
            refreshedAtUtc = DateTimeOffset.UtcNow,
            totalPending = items.Count,
            stageCounts = new
            {
                manager = managerCount,
                pm = projectManagerCount,
                ptc = ptcFinalCount
            },
            access = new
            {
                access.EffectiveUserId,
                access.DisplayName,
                roleCodes = access.RoleCodes,
                access.ScopeLabel,
                access.CanManagerApprove,
                access.CanProjectApprove,
                access.CanPtcFinalApprove,
                access.IsViewAs
            },
            pendingWeeks,
            items
        });
    }

    private static async Task<IResult> BulkCompleteApprovalWorkAsync(
        BulkCompleteRequest request,
        HttpContext context)
    {
        var stage = NormalizeStage(request.Stage);
        if (stage is null)
        {
            return Results.BadRequest(new
            {
                status = "invalid_stage",
                message = "Approval stage must be manager, pm, or ptc."
            });
        }

        if (request.WeekStart is null)
        {
            return Results.BadRequest(new
            {
                status = "week_required",
                message = "Select the pending week to complete."
            });
        }

        await using var connection = new NpgsqlConnection(ConnectionString());
        await connection.OpenAsync(context.RequestAborted);

        var access = await LoadAccessAsync(connection, context, context.RequestAborted);
        if (access is null)
        {
            return Results.Json(new
            {
                status = "session_required",
                message = "A valid Pulse session is required."
            }, statusCode: StatusCodes.Status401Unauthorized);
        }

        if (access.IsViewAs)
        {
            return Results.Json(new
            {
                status = "view_as_read_only",
                message = "Approval decisions are disabled while using Administrator View-As."
            }, statusCode: StatusCodes.Status403Forbidden);
        }

        if (!CanCompleteStage(access, stage))
        {
            return Results.Json(new
            {
                status = "access_denied",
                message = $"The current role cannot complete the {StageLabel(stage)} stage."
            }, statusCode: StatusCodes.Status403Forbidden);
        }

        await using var transaction = await connection.BeginTransactionAsync(context.RequestAborted);
        try
        {
            var candidates = await LoadPendingItemsAsync(
                connection,
                transaction,
                access,
                stage,
                request.WeekStart,
                context.RequestAborted);

            if (request.Items is { Count: > 0 })
            {
                var selected = request.Items
                    .Select(item => ApprovalKey(item.TimesheetId, item.WorkDate))
                    .ToHashSet(StringComparer.OrdinalIgnoreCase);
                candidates = candidates
                    .Where(item => selected.Contains(ApprovalKey(item.TimesheetId, item.WorkDate)))
                    .ToList();
            }

            if (candidates.Count == 0)
            {
                await transaction.RollbackAsync(context.RequestAborted);
                return Results.Ok(new
                {
                    status = "nothing_to_complete",
                    stage,
                    weekStart = request.WeekStart,
                    completedCount = 0,
                    message = "No pending approval items remain for the selected stage and week."
                });
            }

            var hasScopedApprovalAudit = await TableExistsAsync(
                connection,
                transaction,
                "scoped_approval_stage_events",
                context.RequestAborted);

            var systemReason = BuildSystemApprovalReason(access, stage, request.WeekStart.Value);
            var completed = 0;
            var skipped = 0;

            foreach (var item in candidates)
            {
                var changed = await CompleteOneAsync(
                    connection,
                    transaction,
                    access,
                    stage,
                    item,
                    systemReason,
                    hasScopedApprovalAudit,
                    context.RequestAborted);

                if (changed) completed++;
                else skipped++;
            }

            await transaction.CommitAsync(context.RequestAborted);

            return Results.Ok(new
            {
                status = completed > 0 ? "approval_work_bulk_completed" : "nothing_to_complete",
                stage,
                stageLabel = StageLabel(stage),
                weekStart = request.WeekStart,
                weekEnd = request.WeekStart.Value.AddDays(6),
                requestedCount = candidates.Count,
                completedCount = completed,
                skippedCount = skipped,
                commentRequired = false,
                message = completed > 0
                    ? $"Completed {completed} {StageLabel(stage).ToLowerInvariant()} item(s) for the selected week."
                    : "No pending approval items remained when the request was processed."
            });
        }
        catch (Exception exception)
        {
            await transaction.RollbackAsync(context.RequestAborted);
            return Results.Problem(
                title: "Bulk approval could not be completed",
                detail: exception.Message,
                statusCode: StatusCodes.Status500InternalServerError);
        }
    }
}
