DatabaseDirectory /var/lib/clamav
DatabaseOwner nobody
DatabaseMirror database.clamav.net
ScriptedUpdates yes
TestDatabases yes
NotifyClamd /etc/clamav/clamd.conf
Checks 12
Foreground yes
LogTime yes
ConnectTimeout 10
ReceiveTimeout 60
