BEGIN;
DELETE FROM app_role_permissions WHERE app_permission_id IN (SELECT app_permission_id FROM app_permissions WHERE permission_code IN ('VIEW_SECURE_PROJECT_INFORMATION','MANAGE_SECURE_PROJECT_INFORMATION','VIEW_ENTERPRISE_PMO','MANAGE_ENTERPRISE_PMO','VIEW_FLOWHIVE_PRODUCTION','MANAGE_FLOWHIVE_PRODUCTION','APPROVE_FLOWHIVE_BASELINE','EXPORT_PROJECT_MANAGEMENT_ARTIFACTS'));
DELETE FROM app_feature_catalog WHERE feature_code IN ('SECURE_PROJECT_INFORMATION_EXCHANGE','ENTERPRISE_PMO_PROJECT_CONTROLS','FLOWHIVE_PRODUCTION_PLANNING');
DELETE FROM app_permissions WHERE permission_code IN ('VIEW_SECURE_PROJECT_INFORMATION','MANAGE_SECURE_PROJECT_INFORMATION','VIEW_ENTERPRISE_PMO','MANAGE_ENTERPRISE_PMO','VIEW_FLOWHIVE_PRODUCTION','MANAGE_FLOWHIVE_PRODUCTION','APPROVE_FLOWHIVE_BASELINE','EXPORT_PROJECT_MANAGEMENT_ARTIFACTS');
DROP TRIGGER IF EXISTS trg_flowhive_baseline_immutable ON flowhive_baselines;
DROP TRIGGER IF EXISTS trg_project_management_audit_immutable ON project_management_audit_events;
DROP FUNCTION IF EXISTS projectpulse055_block_project_management_evidence_mutation();
DROP TABLE IF EXISTS project_management_audit_events;
DROP TABLE IF EXISTS project_management_artifacts;
DROP TABLE IF EXISTS flowhive_baselines;
DROP TABLE IF EXISTS flowhive_revision_dependencies;
DROP TABLE IF EXISTS flowhive_revision_tasks;
DROP TABLE IF EXISTS flowhive_plan_revisions;
DROP TABLE IF EXISTS flowhive_plans;
DROP TABLE IF EXISTS enterprise_pmo_workbook_imports;
DROP TABLE IF EXISTS enterprise_pmo_status_reports;
DROP TABLE IF EXISTS enterprise_pmo_change_requests;
DROP TABLE IF EXISTS enterprise_pmo_raid_items;
DROP TABLE IF EXISTS enterprise_pmo_projects;
DROP TABLE IF EXISTS secure_project_information_values;
DROP TABLE IF EXISTS secure_project_information_submissions;
DROP TABLE IF EXISTS secure_project_information_requests;
DROP TABLE IF EXISTS secure_project_information_fields;
DROP TABLE IF EXISTS secure_project_information_templates;
DELETE FROM schema_migrations WHERE migration_id='055_project_management_product';
COMMIT;
