import { topic, how, ADMIN, SALES, DELIVERY, ALL } from './guide-model.js';
export default [
  topic('toyota-hyundai-pipelines', SALES.concat(['PROJECT_TEAM_COORDINATOR','PROJECT_MANAGEMENT']), 'Manage customer pipeline context and sales-to-delivery ownership; the legacy route may display the customer-neutral Customer Pipelines title.',
    ['An authorized customer/opportunity, source facts and accountable sales/delivery owners.'], [
      how('Maintain a customer pipeline and handoff', ['Open Customer Pipelines (the legacy route is toyota-hyundai-pipelines).', 'Select the customer/program and review opportunities, ownership and delivery context.', 'Use authorized controls for records, estimates, updates, documents and action items.', 'Check the saved result and resolve missing customer or owner information in its authoritative directory.', 'Pass reviewed scope through Sales Intake, SOW/GSD and Signed Handoff rather than treating a pipeline entry as a project.'], 'The opportunity/program has an owned next action and traceable source information.', 'AE/Inside Sales → SA → delivery intake owner.')
    ], ['The historic route/name does not restrict the platform to only Toyota or Hyundai. Customer/project access remains server scoped.'], ['App.jsx', 'EnterpriseExperienceController.jsx']),
  topic('customer-directory', SALES.concat(['PROJECT_TEAM_COORDINATOR','PROJECT_MANAGEMENT']), 'Maintain permitted customer context while respecting the selected customer source of authority.',
    ['The customer identity and approved Manual, ConnectWise SELL or other configured source selection.'], [
      how('Find, maintain and reconcile a customer', ['Search for an existing customer first to avoid duplicates.', 'Review authoritative source, local contacts, relationships, addresses and related work.', 'Maintain only locally editable fields through the authorized control.', 'For synchronization, inspect provider readiness and preview/mapping results before any supported apply action.', 'Verify the resulting source link and local details; send mapping/provider failures to the integration owner.'], 'The customer has a verified source identity and locally owned enrichment, not a guessed external match.', 'Sales/customer-data owner → SA, PTC and integration administrator.')
    ], ['An available ConnectWise quote API does not establish customer-sync readiness; a reviewed customer adapter may still be required.', 'Changing source authority must not discard existing history or silently overwrite another provider’s fields.'], ['CustomerDirectoryCenter.jsx', 'CustomerSourceAuthorityPortal.jsx', 'docs/modules/module-026-crm-erp-integrations/CONNECTWISE-SELL-SETUP.md']),
  topic('sales-intake', SALES.concat(['PROJECT_TEAM_COORDINATOR']), 'Capture the customer request and route it to an accountable Solution Architect/delivery intake owner.',
    ['Customer, AE, requested outcome, known constraints and supporting source documents.'], [
      how('Submit a complete sales request', ['Find the customer/opportunity and check for an existing intake.', 'Enter the service need, technical scope, dates and known commercial/approval facts.', 'Identify the responsible AE, SA and receiving intake owner using the offered directory choices.', 'Attach supported documents and submit only after required fields validate.', 'Track returned questions or acceptance; continue scope development in Module 025.'], 'A traceable intake request reaches the next owner with missing facts explicitly identified.', 'AE/Inside Sales → Solution Architect and PTC.')
    ], ['Intake does not create a final SOW, reserve resources, authorize delivery or replace Module 055D project creation.'], ['App.jsx', 'WorkIntakeCreationCenter.jsx']),
  topic('sow-generator', SALES.concat(['MANAGER','PROJECT_TEAM_COORDINATOR']), 'The assigned SA authors and reviews the SOW/GSD. Managers oversee their reporting team and may perform only explicitly authorized transfers; delivery LOE is not SA authoring effort.',
    ['An authorized customer, editable Project Name, service scope and accountable AE/SA.', 'Required workspace schemas and Module 064 capability readiness; external complete-scope processing requires its own explicit approval.', 'Exit View-As and finish any in-progress save, generation, work-tracking or ownership action.'], [
      how('Create the request and preserve the source scope', ['Select New SOW / GSD in My Work and choose the customer and editable Project Name.', 'Complete Engagement setup: business/technical outcome, contract and commercial fields, owners and source facts supported by the form.', 'In Service Scope, describe the full technical request, quantities, versions, inclusions, exclusions, constraints and acceptance requirements.', 'Keep Service Scope distinct from the generated Service Overview. For a legacy record, use Use existing input as Service Scope only when deliberately adopting the new source mode.', 'Wait for Saved/autosave confirmation and reload the record before treating the input as persisted.'], 'One versioned SOW/GSD record holds the authored source and the correct identity/commercial facts.', 'AE provides request facts; assigned SA owns the technical scope.'),
      how('Generate and review all five phases', ['Select Generate draft only after the customer and meaningful Service Scope are saved.', 'Follow Plan 1/5, Design 2/5, Implement 3/5, Validate 4/5 and Release 5/5 with their timers.', 'Review the proposed Service Overview independently from its source; use Use this overview proposal only to accept the proposed narrative.', 'For each phase, inspect objectives, task descriptions, deliverables, dependencies/assumptions and AI-suggested versus SA-final hours.', 'Set the reviewed final hours and after-hours portion for the actual tasks; resolve every task-review issue and mark the required phase reviews.', 'If generation fails, preserve the record and prior versions, read the stage/error, and use the offered resume/retry action after addressing the blocker.'], 'A substantive, human-reviewed five-phase proposal exists; failure has not fabricated a complete package or erased the source.', 'Assigned SA → technical/commercial reviewers.'),
      how('Confirm and download a consistent SOW/GSD package', ['Check that detailed scope has been generated, all phase objectives/task hours are reviewed and final LOE is greater than zero.', 'Resolve the requirements listed in Review, confirm & export.', 'Select Confirm Reviewed SOW / GSD and verify the confirmed state; do not work around a disabled gate.', 'Download the confirmed SOW and GSD from Documents & ConnectWise SELL handoff.', 'Verify customer/project/AE/SA fields, task totals, after-hours mapping, branding and formulas in the outputs before sharing.', 'Use an available draft download only as a draft, not a confirmed customer baseline.'], 'Both artifacts derive from the same reviewed task record and version; filenames identify SOW number, Project Name and SOW/GSD type.', 'SA → Inside Sales/AE; reviewed signed package → PTC/PM.'),
      how('Manage work queues, due dates and ownership coverage', ['Use My Work or an authorized Team Work view; filter to the relevant SA/record and inspect due work.', 'Where Work Tracking is enabled, maintain the offered assignment/due-date/effort fields and save or discard those edits before switching records.', 'Open Transfer ownership or arrange PTO coverage, select an eligible teammate and enter a meaningful reason.', 'Choose Permanent ownership transfer or Temporary PTO coverage. For temporary coverage, supply the permitted return date and later record return handoff notes.', 'Confirm the result and notification evidence; the same record and history remain, and the previous owner’s edit access changes according to the transfer.', 'Review assignment and due-date reminder readiness rather than assuming an enabled reminder has delivered email.'], 'Ownership, coverage and tracking changes are saved with their reasons and receiving owner.', 'SA/authorized manager → receiving SA; notification failure → mail administrator.'),
      how('Retain versions, archive, reopen and manage template candidates', ['Use version history to retrieve previously retained documents instead of creating a duplicate record for each download.', 'Archive an eligible completed package or reopen an archived package using the offered governed control.', 'Delete only an eligible unused draft; inspect the confirmation and retained audit/history behavior.', 'Open Templates to review the current output format and retained candidate versions.', 'Authorized managers/administrators may upload a clean template candidate without customer data and record its purpose.', 'Treat a retained candidate as proposed only: do not assume it replaced the active SOW letterhead or GSD formula mapping.'], 'Versions and lifecycle evidence remain attached to one logical package; template retention does not silently change production output.', 'SA → receiving delivery owner; template candidate → authorized template reviewer.'),
      how('Check the ConnectWise SELL handoff before publishing', ['Review the confirmed package, AE/customer mapping and ConnectWise SELL readiness.', 'Use the current supported handoff/submission control only if the configured publisher and record mapping are ready.', 'Inspect the returned receipt and destination record rather than assuming a click uploaded documents.', 'Track notification outcomes for the intended Inside Sales, AE and SA recipients.', 'When publisher/mapping readiness is blocked, retain the reviewed package and use the approved manual handoff; ask the integration owner to resolve the adapter.'], 'The package has a verified publication receipt or an explicitly pending/manual handoff.', 'SA/Inside Sales/AE → PTC and integration owner.')
    ], ['The complete Service Scope field is not automatically anonymized. Do not enter confidential information into an externally approved field unless organizational approval covers that disclosure.', 'Module 064’s saved sow_gsd_planning route is the sequence authority; this guide never hard-codes a provider order.', 'Legacy sanitized approval does not authorize complete Service Scope processing. External refusals, skips, timeouts and invalid task output remain explicit.', 'Managers may have read-only team content even when transfer controls are granted. System SA and Collaboration & Networking SA teams follow the actual reporting/assignment structure, not a guide-created role.', 'A saved template candidate, successful provider health test or available SELL connection does not prove generation, template activation or document publication.'], ['module025/SowGsdAuthoringWorkspace.jsx', 'module025/PhaseTaskReview.jsx', 'module025/OwnershipTransfer.jsx', 'module025/WorkTrackingPanel.jsx', 'module025/TemplateCatalog.jsx', 'module025/SowRegister.jsx', 'docs/module025-service-scope/README.md']),
  topic('crm-integration', ADMIN.concat(['INSIDE_SALES']), 'Authorized integration administrators configure and verify server-side CRM/ERP connections; business users consume only permitted outcomes.',
    ['Approved provider/tenant configuration, intended environment, authorized credentials and reviewed mappings.', 'Use write-only credential fields; never place keys in notes, screenshots, URLs shared with support or source code.'], [
      how('Configure and verify a connector', ['Choose the connector in Integration Control Center, then select Edit or Configure connection.', 'Review the recommended template, endpoint origin, authentication method and non-secret field mappings.', 'Save approved credentials using the secure write-only action and save the connection configuration.', 'Enable the connection only when approved, then select Test availability.', 'Inspect the actual test result, timestamps and diagnostics; independently verify readiness for each consuming workflow.'], 'Configuration is saved and the read-only connection test has a concrete outcome.', 'Integration administrator → customer-data, sales and delivery owners.'),
      how('Set up the current ConnectWise SELL/CPQ connector', ['Select ConnectWise SELL and apply/review the recommended configuration; keep Enabled off until credentials are ready.', 'An authorized tenant administrator supplies the tenant access key and public/private API-key pair.', 'Enter the three keys in Edit connection and select Save credential securely. Do not use a PSA company ID, ordinary account password or unrelated bearer token.', 'Enable/save the connection and run Test availability against the supported quote API.', 'Before quote/pricing import, customer sync or document publication, confirm the tenant mapping and the specific adapter/publisher readiness.'], 'The quote API returns a valid tested result; other actions remain explicitly gated.', 'Tenant/integration administrator → Inside Sales/SA/PTC.')
    ], ['Available means the tested API is available, not that customer sync, labor-rate import or document publishing is implemented/configured.', 'Use the actual quote record ID, not an assumed quote number. Unsupported regional/private origins require a reviewed adapter change.', 'Never retry an uncertain external write until its outcome and idempotency handling are understood.'], ['CrmErpIntegrationCenter.jsx', 'CrmErpTokenPersistencePanel.jsx', 'docs/modules/module-026-crm-erp-integrations/CONNECTWISE-SELL-SETUP.md']),
  topic('sales-insights', SALES.concat(['EXECUTIVE','PROJECT_MANAGEMENT']), 'Review permitted sales and delivery indicators and assign follow-up to the source owner.',
    ['Authorized customer/opportunity/project context and current source data.'], [
      how('Investigate a sales/delivery indicator', ['Select the permitted period, customer or opportunity filters.', 'Review pipeline, source readiness and related project/delivery information.', 'Open supporting records for a material variance or missing source.', 'Correct the source through Customer Directory, Opportunities, Intake or the project workspace as appropriate.', 'Refresh the insight and capture the accountable next action.'], 'The follow-up is tied to a specific source record and owner rather than an inferred dashboard value.', 'AE/Inside Sales → SA, PM or customer-data owner.')
    ], ['Dashboard visibility does not grant invoice, pricing or unrelated-customer access. Partial sources are not zero values.'], ['SalesInsightsDashboard.jsx', 'UnifiedProjectFinancialWorkspace.jsx']),
  topic('certify-integration', ADMIN.concat(['ACCOUNTING','BILLING']), 'Manage the approved expense-provider connection and verify synchronization evidence.',
    ['Approved Certify/expense-provider settings, intended environment and granted integration authority.'], [
      how('Review connection and expense synchronization', ['Open Certify Connection & Sync Center and inspect non-secret connection state.', 'Use the offered configuration/test controls only with approved credentials and scope.', 'Review synchronization readiness, selection and any preview/mapping result before starting a supported sync.', 'Inspect the run result and rejected/unmapped items.', 'Reconcile accepted records against the expense source and Module 005 before using them for billing.'], 'A tested connection and traceable synchronization outcome exist for the intended expense scope.', 'Integration administrator → Accounting and project expense owner.')
    ], ['A healthy connection is not proof every expense was imported. Avoid duplicate syncs when a prior result is unknown.'], ['CertifyIntegrationCenter.jsx']),
  topic('opportunities', SALES, 'Sales owns opportunity qualification and the customer handoff; SA/Inside Sales contribute within assigned-record scope.',
    ['Customer identity, accountable AE, scope/value/date facts and authorized opportunity access.'], [
      how('Maintain an opportunity and move it toward scoping', ['Search for the opportunity/customer before creating a duplicate.', 'Review or maintain the allowed stage, ownership, value, dates and supporting notes/documents.', 'Save the change and confirm its persistent status/history.', 'Use the supported sales intake or SOW/GSD handoff and identify the receiving SA.', 'Track returned questions and actual stage progression rather than assuming a linked draft is a signed sale.'], 'The opportunity has current facts and an accountable scoping/handoff owner.', 'AE → Inside Sales/SA → PTC when signed/approved.')
    ], ['Source-owned CRM fields and pipeline forecasts do not independently create projects, reserve resources or authorize billing.'], ['OpportunitiesCenter.jsx', 'docs/modules/module-063-opportunities/README.md']),
  topic('sales-coverage-alignment', ALL, 'Review sales coverage; authorized sales/SA/PTC/administrative editors maintain only the offered draft or native versioned records.',
    ['Active identity choices, effective dates and approved customer/coverage responsibility.'], [
      how('Review, validate and preserve a coverage change', ['Open the alignment view and inspect current source signals and effective-date context.', 'Use the permitted editor to select real identity records and enter the proposed coverage period.', 'Validate conflicts, required fields and overlapping assignments.', 'If the page labels the work an unsaved draft, export it and do not claim it was persisted.', 'If a separate native administration panel is enabled, save there through its revision-checked workflow and verify reload/history.'], 'The proposed or saved coverage state is explicit and supported by the relevant validation/version evidence.', 'Sales/SA/PTC → coverage manager and affected account owners.')
    ], ['A validated legacy draft and a native persisted document are different surfaces. Neither automatically changes external CRM ownership.'], ['SalesCoverageAlignmentCenter.jsx', 'NativeModuleAdministrationPanel.jsx', 'docs/modules/modules-064-074-native-administration/README.md']),
  topic('oem-vendor-directory', ALL, 'Everyone with module access may consult the directory; authorized administrators, SAs and PTCs may edit the supported draft/native records.',
    ['Accurate vendor identity, contacts, HTTPS support links, products, certifications and status.'], [
      how('Review or validate vendor information', ['Use Vendor directory to search the current list; consult Field guide and Governance for the field contract.', 'Authorized editors select Add vendor or edit the permitted record fields.', 'Check unique vendor names, valid contacts, HTTPS-only support links and the controlled status choices.', 'Select Validate draft, resolve errors and export CSV or JSON when using the unsaved-draft surface.', 'Only use a separately enabled native Save workflow to persist records; verify its revision/history and reload.'], 'A validated exported draft or a separately confirmed native record is retained without confusing the two.', 'SA/PTC/vendor owner → delivery team and directory administrator.')
    ], ['The banner “unsaved draft” means edits are not canonical persistence. Validation/export does not enable imports, external synchronization or public APIs.', 'A vendor listed as active/preferred is an operational record, not automatic approval for purchases or credential access.'], ['OemVendorDirectoryCenter.jsx', 'NativeModuleAdministrationPanel.jsx', 'docs/modules/modules-064-074-native-administration/README.md'])
];
