import { topic, how, ADMIN, ALL, DELIVERY } from './guide-model.js';
export default [
  topic('user-admin', ADMIN, 'Administer identity/account state through approved local or directory-owned workflows without impersonating a worker.',
    ['An approved account request, verified person and understanding of the record’s local/directory source.'], [
      how('Create, update or deactivate an account', ['Search by name/email and inspect the account source before creating a duplicate.', 'For an approved local account, use the offered creation/onboarding controls and supported fields.', 'Update account status or locally editable profile fields; maintain directory-owned values through their source.', 'Complete role assignment through Role Administration rather than editing browser state.', 'Verify effective access and Audit History; communicate onboarding/reset information through the approved secure process.'], 'The intended person has the approved account state and verified access.', 'Administrator → requesting manager/person; directory issues → Module 010/065.'),
      how('Handle a local password-reset request', ['Locate the requester and the active reset request.', 'Use the authorized approval/reset workflow rather than asking for the existing password.', 'Complete any approved temporary-password or reset step in the protected interface.', 'Verify request completion and the corresponding audit/notification outcome.'], 'The reset is attributable and the original credential is never disclosed.', 'Authorized account administrator → requester.')
    ], ['Deactivation, deletion and reset have different effects. Use only the current authorized action and confirmation.', 'Do not change directory identities or retain credentials in notes.'], ['UserAdministrationPanel.jsx', 'LocalAdminPasswordResetApprovalsPanel.jsx', 'LocalAdminPasswordResetClearActions.jsx']),
  topic('azure-admin', ADMIN, 'Own directory-user preview, import and reconciliation while preserving the platform’s existing authentication authority.',
    ['Approved tenant/application context and a ready Microsoft directory connection.'], [
      how('Preview and import directory users', ['Review the selected tenant/application and non-secret connection readiness.', 'Preview directory users and apply the supported filters before importing.', 'Compare candidates with existing users and review identity, manager and team mappings.', 'Import only the approved selected records using the offered synchronization control.', 'Review the run’s successes, conflicts and errors; verify resulting identities and assign roles through Module 012.'], 'The approved people are linked to the intended directory identity without duplicate local users.', 'Directory administrator → user/role administrator and people manager.')
    ], ['Preview is not an import. Directory import does not automatically authorize every module.', 'Use Module 065 for the owning Microsoft connection controls when directed by the page.'], ['App.jsx', 'MicrosoftIntegrationPortal.jsx', 'MicrosoftIntegrationDualConnectionPortal.jsx']),
  topic('work-task-builder', ALL, 'Use Celar AI for evidence-grounded assistance; only authorized administrators manage private-runtime or capability configuration.',
    ['Authorized project/documents or system context, configured Module 064 capability and clear user intent.'], [
      how('Ask for an evidence-grounded answer', ['Open Celar AI/Ask Celar AI in the permitted workspace and choose the relevant project or context.', 'Ask a specific question and attach only supported, authorized documents.', 'Inspect citations, assumptions, source freshness and any missing-evidence or refusal message.', 'Use follow-up questions to resolve uncertainty; verify proposed tasks, hours and technical claims before adopting them.', 'Perform any resulting business action in its owning workflow with the usual review and authorization.'], 'The answer is traceable to available evidence and remains an assistance result, not an approved change.', 'User → responsible project/business owner.'),
      how('Prepare private documents and inspect AI readiness', ['Review the private document pipeline for upload, malware-scan, extraction/OCR, indexing and citation readiness where your role exposes those controls.', 'Check the status of each document/version; resolve rejected, quarantined or unavailable evidence before using it for planning.', 'Authorized operators review RAG, runtime, capability routing and answer-reliability workbenches for the relevant failure.', 'Keep provider order/model selection in Module 064 and private runtime maintenance in Module 084.', 'Where Laya/document-decision controls are available, inspect their explicit evidence and prerequisites; do not treat a configured component as proof of a completed decision.'], 'The intended evidence version is ready or its failure has an accountable owner.', 'Document owner → AI/platform operator.')
    ], ['Private retrieval does not authorize disclosing internal text externally. Complete Service Scope generation has a separate explicit consent boundary.', 'AI proposals cannot silently approve time, publish plans, execute production changes or create customer commitments.', 'Degraded or unavailable providers require diagnosis, not invented results or unapproved fallback reordering.'], ['CelarAiProductionPlatform.jsx', 'CelarAiEnterprisePlatform.jsx', 'PulseAiPrivateDocumentPipelineWorkbench.jsx', 'PulseAiPrivateRagWorkbench.jsx', 'CelarAiAskOperations.jsx', 'PulseAiSystemIntelligenceWorkbench.jsx']),
  topic('role-admin', ADMIN, 'Assign approved business roles and publish scoped policy changes while retaining immutable versions and protected invariants.',
    ['Approved duties, actual signed-in administrative authority and the required policy-management permissions.'], [
      how('Assign a role and verify effective access', ['Find the user and inspect existing role assignments, manager/team and account state.', 'Select the approved role change and its intended data scope using the current directory choices.', 'Use the offered save/validation/publication controls and resolve every safety finding.', 'Verify the published version, permitted modules/actions and at least one expected denial.', 'Use read-only View-As only as a preview where supported; inspect the audit evidence and communicate the result.'], 'The user’s effective access matches the approved duties and scope.', 'Requesting manager/security owner → role administrator → user.'),
      how('Restore a policy without erasing history', ['Identify the known policy version and the reason for restoration.', 'Review the difference and impact on affected roles/modules.', 'Use the governed restore/validate/publish sequence to create a new version.', 'Recheck effective allow/deny behavior and retain the restoration receipt.'], 'The prior intended policy is restored as a new auditable version.', 'Administrator → security and affected role owners.')
    ], ['Not Set preserves existing behavior; it is not an explicit grant. No Access denies module access.', 'Super Administrator’s permanent organization-wide Full Control invariant cannot be reduced. It does not remove audit or environment approvals.'], ['RoleAdminDirectoryPanel.jsx', 'role-permission-model.js']),
  topic('roles-permissions-matrix', ADMIN, 'Explain published role/module/action decisions. The matrix is a reference/export surface, not a substitute for governed role-policy editing.',
    ['The role, module/action and published policy version under review.'], [
      how('Explain why an action is allowed or denied', ['Choose the module and role, or search for a permission/action code.', 'Read the published decision, action description and scope; compare role columns using the pinned context columns.', 'Distinguish Not Set from an explicit Allow or No Access decision.', 'Use access explanation/export where offered and compare the result with the role’s actual responsibility.', 'Make approved policy changes through Module 012 and revisit the matrix after publication.'], 'The access explanation cites a published decision and scope rather than assuming every role has identical controls.', 'Role owner/reviewer → authorized policy administrator.')
    ], ['Viewing the guide or matrix never grants the described permissions. Module visibility and action/record authorization are separate.'], ['RolesPermissionsMatrix.jsx', 'role-permission-model.js']),
  topic('ai-provider-configuration', ADMIN, 'Module 064 is the source of truth for enabled AI providers, consumer-specific routing/order, model choices and approval policy.',
    ['An approved provider/model change, the correct consumer capability and secure server-side credential storage.'], [
      how('Configure provider credentials, health and model choices', ['Select the provider and inspect configured/enabled state, active model, health and circuit/usage information.', 'Store a new key only in the secure write-only credential control; verify the configured indicator without retrieving the secret.', 'Use supported model discovery/refresh and select an approved model suitable for the capability, budget and latency requirements.', 'Enable or disable only approved providers; verify the saved state and run the permitted health/availability check.', 'Investigate Degraded/unavailable status with the returned diagnostics and provider owner.'], 'The saved provider/model configuration and tested health are explicit; live generation success is still a separate check.', 'AI administrator → capability consumers and platform support.'),
      how('Set the sequence used by a specific AI workflow', ['Choose the relevant consumer capability, such as SOW/GSD planning or project planning.', 'Review and edit the offered provider sequence, enabled options and policy/budget limits.', 'Save, reload and confirm the persisted order.', 'Run a separately authorized functional test and compare routing evidence with that saved sequence.', 'On failure, inspect skips, refusal, timeout and circuit evidence; do not insert an undocumented provider or override a safety refusal.'], 'Consumers follow the stored Module 064 sequence for their capability.', 'AI administrator → SA/PM or other workflow owner.'),
      how('Manage external Service Scope processing approval', ['Read the complete-scope disclosure warning and confirm organizational approval covers the actual field contents.', 'Distinguish the legacy sanitized-generation approval from Allow configured AI providers to process the complete Service Scope for SOW/GSD generation.', 'Save only the intended approval with the current revision and reload to verify it.', 'Revoke that approval through the same governed control when no longer authorized.', 'Leave provider order unchanged unless a separate approved routing change is intended.'], 'External complete-scope disclosure is explicitly authorized or disabled independently of routing order.', 'Authorized policy owner → AI administrator → SA authors.')
    ], ['Do not hard-code an old DeepSeek/Celar/Claude/OpenAI order in instructions; use the current saved configuration.', 'Gemini, Copilot or another listed provider may still require a supported adapter, credentials, model and enablement; listing is not readiness.', 'Private Celar runtime health is visible here, while its maintenance schedule is owned by Module 084.', 'Provider tests can incur requests/cost; keep them within the approved environment and data scope.'], ['AiProviderConfigurationCenter.jsx', 'ai/AiProviderReadinessPanel.jsx', 'CelarAiProviderBridgePanel.jsx', 'NativeModuleAdministrationPanel.jsx', 'docs/module025-service-scope/README.md']),
  topic('entra-secret-administration', ADMIN, 'Manage the configured Microsoft SSO, services/Graph and notification connection surfaces; privileged credential rotation remains separately guarded.',
    ['Approved tenant/client, intended environment, requested permissions, sender/transport settings and required administrator authority.'], [
      how('Review and configure Microsoft integration', ['Open Microsoft Integration Connection and distinguish Microsoft Entra SSO from Microsoft services and Graph.', 'Select the intended tenant/profile; inspect identity permissions, client-secret configured state and expiry without exposing the value.', 'Use the approved secure credential and connection controls, then configure the supported sender/transport settings.', 'Run the offered Microsoft Graph/connection test and inspect the actual permission/readiness results.', 'Verify the dependent directory, calendar, project notification or Teams capability separately and retain sanitized evidence.'], 'The intended connection is saved and tested without confusing sign-in readiness with service-delivery readiness.', 'Microsoft integration administrator → identity, calendar and notification owners.'),
      how('Handle Teams notifications and credential expiry', ['Review the supported Teams notification settings and target readiness when the panel is available.', 'Configure only approved destinations/policies; verify the recorded test or delivery outcome rather than assuming configuration sends a message.', 'Review expiry warnings and the current credential lifecycle state.', 'Use privileged prepare/test/activate/rollback controls only if all required adapters, approvals and recent step-up authorization are available.', 'If the lifecycle is locked, escalate the missing prerequisite instead of treating ordinary metadata Save as rotation.'], 'Notification and credential-lifecycle states are evidenced independently.', 'Integration administrator → Teams/mail owner or privileged credential owner.')
    ], ['SSO, Graph, mail and Teams readiness are separate. Browser-provided recipients are not notification authority.', 'A locked rotation adapter or missing step-up gate must not be bypassed. View-As cannot change credentials or deliver notifications.'], ['MicrosoftIntegrationPortal.jsx', 'MicrosoftIntegrationDualConnectionPortal.jsx', 'MicrosoftTeamsNotificationPanel.jsx', 'EntraSecretAdministrationCenter.jsx', 'EntraSecretExpirationGovernancePanel.jsx']),
  topic('global-mail-configuration', ADMIN, 'Review the shared outbound-mail consumer and transport configuration; use the owning Microsoft/global-mail controls rather than per-module credentials.',
    ['The correct environment, approved sender/transport, recipient boundary and current configuration authority.'], [
      how('Verify outbound-mail readiness', ['Inspect the Microsoft 365/global mail target, sender metadata and consumer registry.', 'Follow the owning connection control when configuration is managed by Module 065.', 'Review recipient policy, enabled state, credential readiness and any locked migration/delivery boundary.', 'Run only the supported approved test and verify the actual receipt.', 'Use dispatch/operational evidence to trace failed or held notifications and coordinate an authorized retry.'], 'Transport configuration and the actual delivery result are clearly separated.', 'Mail administrator → all consuming workflow owners.')
    ], ['Non-secret metadata Save does not activate SMTP, rotate a secret or prove email delivery. No module should duplicate provider credentials in a note.'], ['GlobalMailConfigurationCenter.jsx', 'MicrosoftMailTransportReadinessPanel.jsx', 'docs/modules/module-067-global-mail/README.md']),
  topic('system-architecture', ADMIN.concat(['EXECUTIVE']), 'Review the provider-neutral system and dependency map and maintain only authorized curated metadata.',
    ['Current registry/source evidence and any separately granted architecture-editor authority.'], [
      how('Trace a module or system dependency', ['Select the system/provider/module view and inspect connected APIs, data flows, identity and environment context.', 'Check source timestamps, region/redundancy and live-status evidence before treating the diagram as current.', 'Use permitted curated-record editing only for approved architecture metadata.', 'Generate the branded export and retain the source/revision context.', 'Route a missing dependency or readiness signal to its owning team.'], 'The diagram/export explains the actual registered relationships and their evidence limitations.', 'Architecture/platform owner → integration, reliability and delivery teams.')
    ], ['A diagram node is not a live health check or deployment approval.'], ['SystemArchitectureCenter.jsx', 'NativeModuleAdministrationPanel.jsx', 'docs/modules/module-068-system-architecture/README.md']),
  topic('integration-event-gateway', ADMIN, 'Integration operators inspect source contracts, delivery evidence and dead-letter policy; execution requires the specific approved connector and action authority.',
    ['Source owner, versioned contract, authentication/signature policy, idempotency and correlation identifiers.'], [
      how('Review an event integration and resolve delivery exceptions', ['Inspect Overview, Sources, Contracts, Deliveries, Dead-letter policy and Security policy.', 'Identify missing setup/adapter prerequisites and the actual source owner.', 'Review envelope validation, event/delivery identity, signature and idempotency requirements before enabling a source.', 'For a failed delivery, inspect existing attempts and resolve uncertainty before any supported retry/replay/quarantine action.', 'Use Open owning control for the approved configuration and retain the resulting evidence.'], 'The source or exception has a verified readiness/attempt state and accountable next action.', 'Integration operator → source-system owner and support.')
    ], ['Selectable sections or stored metadata do not mean webhook intake, connector calls, replay or external delivery is enabled.', 'Do not replay an uncertain external write merely to make the screen look successful.'], ['IntegrationEventGatewayCenter.jsx', 'GovernedOperationalReadCenter.jsx']),
  topic('defect-tracker', ALL, 'Report issues and feature requests with reproducible, sanitized evidence; authorized owners triage and resolve them.',
    ['Module/route, time, expected/actual behavior and non-sensitive reproduction evidence.'], [
      how('Create, triage and close a defect', ['Choose Report an Issue or Feature Request and identify the affected module.', 'Describe the steps, expected result, actual result, severity/impact and any correlation reference.', 'Review local draft and remove credentials or unnecessary customer/personal data.', 'Select Create defect only when durable intake readiness is available; verify the returned defect ID.', 'Authorized owners assign, investigate and update the record. Retest the reported behavior and retain resolution evidence before closing.'], 'A durable, owned issue exists or the interface explicitly reports that intake is not ready.', 'Reporter → manager/assigned resolver → reporter for verification.')
    ], ['An unsaved draft is not a submitted defect. AI preparation or external-sync configuration is not proof of a synchronized issue.'], ['DefectTrackerCenter.jsx', 'CelarAiAskOperations.jsx', 'docs/modules/module-076-defect-tracker/README.md']),
  topic('release-deployment-control', ADMIN, 'Platform release owners review immutable releases, environment approvals, gates, verification and rollback evidence.',
    ['Approved change scope, exact release identity, target environment, passing checks and a retained rollback baseline.'], [
      how('Review a controlled release', ['Inspect Overview, Releases, Environments, Gates, Evidence and Rollback policy.', 'Confirm the intended source revision, immutable artifact identity and target environment.', 'Resolve failing gates or missing approval/adapter evidence before execution.', 'Use only the existing protected release workflow with its required authorization and concurrency controls.', 'Verify the installed version, health and scoped acceptance, and record the actual result or authorized rollback.'], 'The release outcome is tied to an exact artifact and target environment.', 'Release owner → reviewer/operator → testers and service owner.')
    ], ['A successful build or merged PR is not a completed deployment. A selectable release surface does not authorize Production.', 'Do not disable protections, skip checks or cancel another active deployment to force a release.'], ['ReleaseDeploymentControlCenter.jsx', 'GovernedOperationalReadCenter.jsx']),
  topic('observability-slo-health', ADMIN.concat(['EXECUTIVE']), 'Reliability owners interpret service health, SLOs, telemetry and alert evidence, and assign operational follow-up.',
    ['Current telemetry sources, service ownership, time window and defined objectives.'], [
      how('Investigate a reliability signal', ['Inspect the available service, SLO, alert, dependency and telemetry sections.', 'Confirm source freshness, service/environment and the selected measurement period.', 'Compare the signal with its objective and inspect supporting sanitized logs/traces or dependency evidence.', 'Assign an incident or diagnostic follow-up to the owning team.', 'Recheck health after an approved repair and preserve the before/after evidence.'], 'The reliability decision is grounded in current telemetry and an accountable response.', 'Reliability owner → service/incident owner.')
    ], ['No telemetry is not healthy telemetry. Connecting an observation source does not grant remediation authority.'], ['ObservabilitySloHealthCenter.jsx', 'GovernedOperationalReadCenter.jsx']),
  topic('data-governance-retention', ADMIN, 'Data owners govern classification, retention, legal hold and reviewed disposition without bypassing evidence or approval.',
    ['Approved domain ownership, classification/retention policy and any required legal-hold/disposition adapter.'], [
      how('Review policy and proposed disposition', ['Inspect the available catalog, policy, retention, hold and evidence sections.', 'Identify the accountable data owner and the source/classification of the affected records.', 'Review eligibility, dependencies and legal holds before proposing a retention/disposition action.', 'Use only an authorized preview/approval workflow; a missing adapter or hold blocks destructive execution.', 'Retain the reviewed scope and actual outcome, and verify required evidence remains accessible.'], 'Policy and disposition decisions remain attributable and respect holds and retention obligations.', 'Data owner → governance/legal reviewer → authorized operator.')
    ], ['A policy record is not proof data was deleted. Never remove evidence to clear a warning.'], ['DataGovernanceRetentionCenter.jsx', 'GovernedOperationalReadCenter.jsx']),
  topic('full-future-loop', ADMIN, 'Authorized operators manage the persistent sandbox’s reviewed development, verification, repair and re-promotion sequence.',
    ['An approved sandbox test, precise scope, environment and authorized repositories/connectors.'], [
      how('Follow a governed sandbox loop', ['Create/select the permitted Full Future Loop test and review its scope and linked systems.', 'Track STEER-IT/governance, Private Dev Repo, canary verification and curated promotion stages.', 'Review Production Evidence as read-only evidence; do not assume it permits production mutation.', 'Use Watcher/Issue Relay and Private Repair Issue to assign a repair, then review the proposed fix.', 'Re-promote only through the required approvals and verify via canary runs.', 'Inspect Evidence, Agent Keep and Timeline for the actual terminal result and unresolved items.'], 'The loop records reviewed transitions and verification evidence instead of equating activity with success.', 'Governance owner → developer/reviewer → canary/release operator → support.')
    ], ['A sandbox guide is not permission to alter Production or connect new repositories. Failed or blocked stages remain explicit.'], ['FullFutureLoopCenter.jsx', 'FullFutureLoopAutomationCenter.jsx', 'docs/modules/module-083-full-future-loop/README.md']),
  topic('celar-ai-runtime-version', ADMIN, 'Review the private Celar runtime and manage the permitted maintenance window. Module 064 still owns provider order and external model routing.',
    ['Actual administrator authority, a ready private-runtime status service and separate schedule-mutation readiness.'], [
      how('Check versions and change a permitted maintenance window', ['Open Celar AI Runtime & Version Center and review gateway/Ollama, model artifacts/digests, OCR and malware-scanner status.', 'Inspect last attempt, last successful update, rollback availability and current maintenance policy.', 'Compare the next update in Central time and your browser’s local time.', 'If schedule editing is configured and approved, set automatic maintenance, day, local time and the supported IANA time zone, then Save maintenance window.', 'Reload to confirm the saved policy and inspect the next calculated window/history.'], 'Runtime and maintenance facts are visible and the approved schedule is persisted without changing provider order.', 'Private-runtime administrator → AI/service owners.')
    ], ['Refreshing approved model tags does not silently approve a new model family.', 'Schedule Save does not run arbitrary commands or establish immediate maintenance execution. Missing maintenance authorization stays blocked.'], ['CelarAiRuntimeVersionCenter.jsx', 'docs/modules/module-084-celar-ai-runtime-version/README.md']),
  topic('security-operations', ADMIN, 'Authorized security operators investigate session/authentication evidence and manage reviewed incident/containment workflows.',
    ['An authorized incident scope, current evidence and the required response approvals/connectors.'], [
      how('Investigate and prepare a controlled response', ['Review Active identity sessions and Authentication anomalies for the relevant period/environment.', 'Declare an incident only with factual impact, scope and supporting references.', 'Review the incident case and use Prepare a controlled response/Prepare containment for the bounded proposed action.', 'Obtain the required approval and verify connector readiness before any permitted execution.', 'Inspect the actual containment result, follow-up evidence and case history before resolution.'], 'The incident and response have accountable evidence and explicit approval/execution states.', 'Security operator → authorized incident/containment approver and service owner.')
    ], ['A prepared response is not executed containment. Never terminate sessions or activate a connector outside the approved scope.'], ['SecurityOperationsResponseCenter.jsx', 'docs/modules/module-997-security-operations-response/README.md']),
  topic('system-diagnostics', ADMIN, 'Run authorized diagnostics and prepare bounded, reviewed remediation; diagnose before changing a service.',
    ['Affected environment/service, reproducible symptom, permitted diagnostic scope and action approvals.'], [
      how('Diagnose and request controlled remediation', ['Run a diagnostic session for the permitted target and inspect Live native checks.', 'Review the session’s results, dependencies and sanitized correlation evidence.', 'Choose an applicable runbook and use Prepare remediation to preview the bounded change.', 'Obtain required approvals and verify the specific provider/restart control is configured before any execution.', 'After an approved action, rerun health checks and retain its outcome or rollback evidence.'], 'The diagnostic and any repair are separate, attributable operations with verified results.', 'Support/operator → authorized remediation approver → service owner.')
    ], ['Preparing a runbook is not executing it. Do not restart Azure resources or alter environment settings from a diagnosis alone.'], ['SystemDiagnosticRemediationCenter.jsx', 'docs/modules/module-998-system-diagnostic-remediation/README.md'])
];
