import { topic, how, ALL, ADMIN, FINANCE } from './guide-model.js';
export default [
  topic('timesheet', ALL, 'Each worker records and submits their own time. Authorized time stewards correct records through delegated controls; they do not submit for another person.',
    ['An active assignment or permitted non-project category; the correct week and work date.', 'Exit View-As before writing. Check whether the day is draft, submitted, approved, or locked.'], [
      how('Enter, save and submit your week', ['Choose the week and add the assigned task or non-project activity from Activities.', 'Use Weekly Grid, Daily Focus or Quick Entry List. Enter Normal and Afterhours separately, with location and a meaningful work description.', 'Save draft to retain work in progress. Complete missing descriptions and task associations before submission.', 'Select Submit week, review the validation summary, and confirm. Correct any listed errors rather than repeatedly submitting.', 'Check the resulting submitted state in Approval Inbox; return to the draft only through the supported return or reopen workflow.'], 'The saved entries match the intended dates and tasks; submitted time has entered Module 002, not yet final approval.', 'Worker → Manager → authorized Project Manager/PTC stages → Accounting.'),
      how('Use timers and recover an active timer', ['Open the assigned activity and start its timer; check the running indicator.', 'Keep different activities identifiable. The current timer implementation supports up to five distinct activity timers per user.', 'Stop the timer when the work ends and review its work date, Normal/Afterhours classification, description and rounded hours.', 'Review any recovery or maximum-duration message before saving; do not add a duplicate manual entry for the same work.', 'Save the resulting draft, then submit your own time when ready.'], 'Server timestamps remain auditable; rounded time is reviewed before submission. Each timer is capped at 24 hours and rounds upward once to a quarter hour.', 'Worker retains responsibility for the accuracy of timer-derived time.'),
      how('Correct returned time or act as an authorized time steward', ['For your own returned day, read the reviewer’s reason, correct the draft and resubmit.', 'For delegated correction, select the worker in the time-steward panel, inspect the original entry and provide the required reason.', 'Use the offered reopen, correction, replacement-task/assignment or draft-removal control; verify before-and-after audit evidence.', 'Use Module 001B for administrative task/project reallocation when that is the intended workflow, rather than reopening solely to move time.', 'Tell the worker when resubmission is required. Never use their session or submit on their behalf.'], 'The correction is auditable and follows the selected correction path, with the appropriate approval state.', 'Time steward → worker and the next authorized reviewer.')
    ], ['A saved draft is not submitted or approved time. Vacation/PTO and company Holiday are different categories.', 'Timer limits are application limits, not expected working hours. Stop timers when work stops.', 'Use the approval and billing locks shown by the server; guide visibility never overrides them.'], ['App.jsx', 'PtcTimeEntryCorrectionPanel.jsx', 'role-permission-model.js', 'src/frontend/project-time-web/scripts/generate-module-001-integrated-app.mjs', 'src/frontend/project-time-web/scripts/inject-module-001-owned-extension-slots.mjs']),
  topic('engineer-task-closeout', ['ENGINEERING', 'ENGINEERING_LEAD', ...ADMIN], 'The assigned engineer closes eligible request work, not the entire customer project.',
    ['An assigned Service Request, Pre-Sales or Internal task eligible for engineer closeout.', 'Completion evidence and the current billing/closure state.'], [
      how('Close or reopen eligible request work', ['Select the assigned request/task and review its hours and completion details.', 'Confirm that the work is complete and record the requested completion evidence.', 'Use the closeout action and verify the closed state and history entry.', 'For a correction, use the governed reopen control and enter a reason only while the task remains eligible.', 'If Module 055C has finalized closure, escalate to the project owner rather than trying to bypass the final lock.'], 'The eligible task is closed and additional billing is locked, with an attributable history record.', 'Engineer → Project Team Coordinator or delivery owner.')
    ], ['This action does not close an entire project, close another engineer’s request, or supersede final Work Register closure.'], ['EngineerTaskCloseoutCenter.jsx', 'docs/modules/module-001a-engineer-request-closeout/README.md']),
  topic('time-reallocation', ['PROJECT_TEAM_COORDINATOR', 'SUPER_ADMINISTRATOR'], 'Authorized PTCs and Super Administrators correct the administrative allocation of existing time while preserving the original evidence.',
    ['An identified source entry, permitted destination project/task and an approved correction reason.'], [
      how('Move time without creating a duplicate entry', ['Find the worker, period and source entry; review hours, original project/task and workflow state.', 'Choose the authorized destination and confirm the required project/task assignment.', 'Enter the correction reason and review the proposed before-and-after change.', 'Commit only once and inspect the correction receipt and immutable history.', 'Confirm downstream project/time totals and inform the responsible reviewers of the administrative change.'], 'Time remains traceable to the original entry; administrative reallocation follows Module 001B’s no-worker-resubmission rules.', 'PTC/Super Administrator → project owner and Accounting when financial records are affected.')
    ], ['Module 001B is restricted to Project Team Coordinator and Super Administrator. A generic Administrator role is not sufficient. Administrative reallocation is not the same as returning a worker’s time for correction. Do not instruct the worker to submit a duplicate.', 'Locked or ineligible records must use the available governed workflow; no permanent evidence-free deletion.'], ['module001b/Module001BTimeReallocationPortal.jsx', 'src/backend/ProjectTime.Api/Modules/Module001BTimeReallocationModule.cs', 'role-permission-model.js']),
  topic('manager-approval', ['MANAGER', 'PROJECT_MANAGEMENT', 'PROJECT_MANAGEMENT_LEAD', 'PROJECT_TEAM_COORDINATOR', ...ADMIN], 'Review only the approval stages and records actually granted to your session. Manager, project review and PTC final review are separate responsibilities.',
    ['Submitted, actionable time in your authorized people/project scope.', 'A specific correction reason for any rejection.'], [
      how('Review and decide submitted time', ['Open Approvals in the shared header or Module 002.', 'Select the applicable review stage and filter to the worker/project/date you need.', 'Read descriptions, task association, work date, Normal/Afterhours hours and any prior decision evidence.', 'Approve accurate eligible entries, or return/reject with a specific reason explaining what must change.', 'Check the updated queue, remaining stage and decision history. When using a bulk action, review the selected records and any partial failures.'], 'A recorded decision advances or returns only eligible records; the actionable count refreshes.', 'Reviewer → worker for correction, or the next authorized review stage.'),
      how('Handle administrative approval work', ['Open the password-reset queue only when your role is authorized for that queue.', 'Verify the requester and reset request before deciding; handle any temporary-password step using the approved account workflow.', 'Administrators may use the offered stale-item resolution for eligible submitted items at least seven days old.', 'Verify the audit result and notification outcome; a queued notification is not proof of receipt.'], 'The request has an attributable decision; stale time is returned to its owner without erasing history.', 'Authorized administrator → requester/time owner.')
    ], ['Draft, returned, completed and cancelled items are not actionable approvals.', 'PTC’s role-specific final-review/delegation permissions must be present; module visibility alone does not grant them.', 'Project Manager access does not grant the password-reset queue.'], ['ApprovalCenter.jsx', 'ManagerApprovalPanel.jsx', 'ProjectManagerApprovalPanel.jsx', 'ApprovalMailbox.jsx', 'AdministrativeApprovalRequestsPanel.jsx', 'docs/modules/module-002-approval-center/README.md']),
  topic('utilization', ALL, 'Workers review their own utilization; managers and leads review only their authorized team or reporting scope.',
    ['The reporting year/quarter, configured target, and eligible source time.'], [
      how('Explain a utilization result', ['Choose the relevant year and quarter.', 'Review target percentage/hours, eligible billable hours and remaining hours.', 'Where available, open the team or engineering-lead view and use only the permitted person/team selector.', 'Investigate gaps in source time, approvals or classification in the owning workflow.', 'Refresh the report after the correction is confirmed and note any missing-data message.'], 'The result is interpreted against the selected period and policy, rather than treated as an editable time record.', 'Worker/lead → time owner or authorized policy administrator.')
    ], ['Available allocation, logged hours and utilization-eligible hours are different measures. Missing data must not be interpreted as zero.'], ['YearlyUtilizationPanel.jsx', 'ManagerTeamUtilizationPanel.jsx', 'EngineeringTeamLeadUtilizationPanel.jsx']),
  topic('holiday-admin', ALL, 'Everyone may consult permitted holiday information; authorized administrators maintain the company calendar.',
    ['The correct year and approved company holiday dates.'], [
      how('Review or maintain holidays', ['Choose the year and review the displayed company holidays.', 'For an authorized upload or edit, use the page’s supported format and validate dates and duplicates first.', 'Apply only approved calendar changes.', 'Confirm the dates after reloading and check their downstream appearance in timesheet/calendar workflows.'], 'The intended company holidays are present in the selected year.', 'Calendar administrator → workers and project/resource planners.')
    ], ['Do not enter personal PTO as a company Holiday. Use the current rolling year options instead of assuming a fixed year list.'], ['App.jsx', 'rolling-year-window.js']),
  topic('project-allocation-info', ['ENGINEERING', 'PROJECT_MANAGEMENT', 'PROJECT_TEAM_COORDINATOR', 'ACCOUNTING', 'BILLING', ...ADMIN], 'Upload and reconcile supported project expense evidence within the current record scope.',
    ['A supported expense file, the correct project and required allocation/currency details.'], [
      how('Import, review and verify expenses', ['Open Project Expense Upload and select the permitted project/source context.', 'Choose the supported local file and review the parsed rows before saving.', 'Resolve validation errors, duplicate/mapping warnings and missing allocation fields.', 'Commit the reviewed expense data only when the page permits it.', 'Reload the project’s expenses and confirm the current, non-deleted records used by reporting and billing.'], 'Valid expenses are associated with the intended project and their import outcome is visible.', 'Uploader → project owner and Accounting for financial review.')
    ], ['A parsed file is not a committed expense record. Do not silently substitute a currency, rate or project for a missing source value.'], ['ProjectAllocationInfoPanel.jsx', 'Module005ExperienceCompatibility.jsx', 'ProjectExpenseCrossModulePortal.jsx']),
  topic('workflow', FINANCE.concat(['PROJECT_MANAGEMENT', 'PROJECT_MANAGEMENT_LEAD']), 'Complete the authorized approval, reconciliation, export and lock stages after upstream time review.',
    ['Eligible time, completed upstream approvals, correct period and authorized export/reconciliation access.'], [
      how('Prepare reconciled time for export', ['Choose the period and inspect the eligible workflow records.', 'Resolve PM review or accounting-readiness blockers before reconciliation.', 'Perform only the reconciliation/lock action offered for your role and the record’s current state.', 'Run export validation, review the selected records and generate the supported Excel/PDF package.', 'Retain the export and audit reference, and separately verify any downstream import or posting.'], 'A traceable export/reconciliation result exists for the intended records and period.', 'PM/PTC → Accounting → receiving financial-system owner.')
    ], ['Downloading a package does not prove it was received, invoiced or paid. Locked periods need an authorized correction path.'], ['ApprovalExportAuditWorkflowCenter.jsx']),
  topic('audit-history', ['MANAGER', 'PROJECT_MANAGEMENT', 'PROJECT_TEAM_COORDINATOR', 'ACCOUNTING', ...ADMIN], 'Review authorized immutable evidence, not edit or erase the history.',
    ['A time range, actor/target or correlation reference and audit-view authority.'], [
      how('Trace an action', ['Set the event/date filters and search for the actor, target or relevant record.', 'Open the event and compare the action, actual/effective identity, timestamp and before/after details available.', 'Follow the record’s related version or workflow receipt.', 'Export permitted evidence when needed and redact unnecessary personal/customer information before sharing.'], 'The investigation can cite the exact recorded action rather than infer it from the current screen.', 'Reviewer → accountable workflow owner or security/support.')
    ], ['Not every browser interaction is an audit event. Absence of a selected event does not prove no activity occurred.'], ['AuditHistoryPanel.jsx']),
  topic('time-compliance', ['MANAGER', 'PROJECT_TEAM_COORDINATOR', 'PROJECT_MANAGEMENT', ...ADMIN], 'Identify missing or late time and govern reminder schedules without submitting time for workers.',
    ['The review period, authorized team/user scope and configured notification transport.'], [
      how('Review exceptions and configure authorized reminders', ['Select the period and inspect missing/late submission exceptions.', 'Contact the time owner or use the authorized reminder action; verify the resulting notification state.', 'Administrators open schedule settings and set schedule type, local day/time, IANA time zone, reminder and escalation choices.', 'Review quiet hours, enabled state and the delivery boundary before saving.', 'Check Module 032 or the owning mail evidence for queued, held, sent or failed outcomes.'], 'Exceptions have an owner and scheduled reminders have a saved policy and traceable dispatch outcome.', 'Manager/PTC → worker; administrator → mail/notification owner.')
    ], ['A test-only or locked delivery boundary does not send external mail. Reminder completion is not timesheet submission.'], ['TimeComplianceCenter.jsx', 'TimeComplianceEmailNotificationsPanel.jsx', 'docs/modules/group-4-project-notifications/README.md']),
  topic('ai-time-entry', ALL, 'Use AI assistance to prepare a suggestion, retaining personal responsibility for the final time record.',
    ['Authorized assigned work, factual work notes and an enabled AI capability governed by Module 064.'], [
      how('Review an AI-assisted time suggestion', ['Open AI Time Entry or the offered timesheet work-log assistant.', 'Provide factual work notes without credentials or unnecessary sensitive information.', 'Request suggestions and inspect the proposed task, date, hours and description.', 'Correct unsupported assumptions and confirm only the intended suggestions into the draft.', 'Verify the draft and submit your own time through Module 001.'], 'Human-reviewed suggestions become draft entries; AI has not independently approved or submitted them.', 'Worker → normal time-review chain.')
    ], ['A provider failure must not create fabricated hours or tasks. Use direct entry when appropriate; never treat an AI estimate as proof of work.'], ['App.jsx', 'docs/48-help-assistant-and-timesheet-persistence-validation.md'])
];
