#!/usr/bin/env bash
# Build both images locally and pin them into .verity/release.env, so ./deploy.sh
# can run fully offline (no GHCR / GitHub Release needed). Use for local
# iteration; CI releases use release.yml + scripts/verity/pin-digests.sh instead.
#
# Usage: scripts/verity/build-local.sh [tag]   # tag defaults to "local"
set -Eeuo pipefail
umask 077

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
TAG="${1:-local}"
[[ "$TAG" =~ ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$ ]] || { echo 'Invalid local image tag' >&2; exit 1; }

echo "== Building projectpulse/api:${TAG} =="
docker build -f deployment/containers/api/Dockerfile -t "projectpulse/api:${TAG}" .

echo "== Building projectpulse/web:${TAG} =="
docker build -f deployment/containers/web/Dockerfile -t "projectpulse/web:${TAG}" .

API_IMAGE="$(docker image inspect --format '{{.Id}}' "projectpulse/api:${TAG}")"
WEB_IMAGE="$(docker image inspect --format '{{.Id}}' "projectpulse/web:${TAG}")"
LOCAL_ENV="$(mktemp)"
trap 'rm -f "$LOCAL_ENV"' EXIT
cat > "$LOCAL_ENV" <<EOF
# Generated by scripts/verity/build-local.sh — immutable local image IDs.
RELEASE_TAG=v0.0.0-local
RELEASE_VERSION=0.0.0-local
WEB_IMAGE=${WEB_IMAGE}
API_IMAGE=${API_IMAGE}
EOF
python3 scripts/verity/release-config.py env "$LOCAL_ENV" --output .verity/release.env

echo "Wrote .verity/release.env:"
cat .verity/release.env
