#!/usr/bin/env bash
# Build both images locally and pin them into .verity/release.env, so ./deploy.sh
# can run fully offline (no GHCR / GitHub Release needed). Use for local
# iteration; CI releases use release.yml + scripts/verity/pin-digests.sh instead.
#
# Usage: scripts/verity/build-local.sh [tag]   # tag defaults to "local"
set -Eeuo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
TAG="${1:-local}"

echo "== Building projectpulse/api:${TAG} =="
docker build -f deployment/containers/api/Dockerfile -t "projectpulse/api:${TAG}" .

echo "== Building projectpulse/web:${TAG} =="
docker build -f deployment/containers/web/Dockerfile -t "projectpulse/web:${TAG}" .

cat > .verity/release.env <<EOF
# Generated by scripts/verity/build-local.sh — local iteration only (tag refs, not digests).
RELEASE_TAG=local-${TAG}
RELEASE_VERSION=0.0.0-local
WEB_IMAGE=projectpulse/web:${TAG}
API_IMAGE=projectpulse/api:${TAG}
EOF

echo "Wrote .verity/release.env:"
cat .verity/release.env
