#!/usr/bin/env bash
# Auto-pin the released image digests into .verity/release.env.
#
# Reads the digest manifest (release-digests.json) that release.yml attached to a
# GitHub Release and writes the pinned, by-digest image refs that deploy.sh /
# deploy.compose.yml consume. Never hand-copy digests — always run this.
#
# Usage:
#   scripts/verity/pin-digests.sh [vX.Y.Z]     # defaults to the latest release
set -Eeuo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${REPO_ROOT}/.verity/release.env"
TAG="${1:-}"

command -v gh >/dev/null 2>&1 || { echo "gh CLI required" >&2; exit 1; }

if [ -z "$TAG" ]; then
  TAG="$(gh release view --json tagName -q .tagName)"
fi
echo "Pinning digests from release ${TAG}"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
gh release download "$TAG" --pattern release-digests.json --dir "$TMP" --clobber

manifest="${TMP}/release-digests.json"
version="$(jq -r '.version' "$manifest")"
web="$(jq -r '.images.web' "$manifest")"
api="$(jq -r '.images.api' "$manifest")"

for ref in "$web" "$api"; do
  case "$ref" in
    *@sha256:*) : ;;
    *) echo "Refusing to pin non-digest ref: $ref" >&2; exit 1 ;;
  esac
done

cat > "$OUT" <<EOF
# Generated by scripts/verity/pin-digests.sh — do not edit by hand.
# Byte-identical digests promoted staging -> prod for release ${TAG}.
RELEASE_TAG=${TAG}
RELEASE_VERSION=${version}
WEB_IMAGE=${web}
API_IMAGE=${api}
EOF

echo "Wrote ${OUT}:"
cat "$OUT"
