#!/usr/bin/env bash
set -Eeuo pipefail

MODULE_SLUG="${1:-}"
MODULE_TITLE="${2:-}"

if [ -z "$MODULE_SLUG" ] || [ -z "$MODULE_TITLE" ]; then
  echo "Usage: scripts/scaffold-module.sh <module-slug> <ModuleTitleNoSpaces>"
  echo "Example: scripts/scaffold-module.sh project-intake ProjectIntakeCenter"
  exit 1
fi

REACT_FILE="src/frontend/project-time-web/src/${MODULE_TITLE}.jsx"
CSS_FILE="src/frontend/project-time-web/src/${MODULE_SLUG}.css"
HELP_FILE="docs/help/${MODULE_SLUG}.md"

mkdir -p src/frontend/project-time-web/src docs/help

if [ ! -f "$REACT_FILE" ]; then
cat > "$REACT_FILE" <<REACT
import './${MODULE_SLUG}.css';

export default function ${MODULE_TITLE}() {
  return (
    <section id="${MODULE_SLUG}" className="enterprise-module-shell">
      <div className="module-header-row">
        <div>
          <p className="eyebrow">ProjectPulse Module Scaffold</p>
          <h2>${MODULE_TITLE}</h2>
          <p className="muted">
            Placeholder module generated by scripts/scaffold-module.sh.
          </p>
        </div>
        <span className="dry-run-badge">Scaffold</span>
      </div>

      <div className="module-grid">
        <article className="module-card">
          <h3>Frontend page</h3>
          <p>React shell is ready for demo wiring.</p>
        </article>
        <article className="module-card">
          <h3>Backend endpoint</h3>
          <p>Map an API endpoint placeholder in Program.cs or a module extension file.</p>
        </article>
        <article className="module-card">
          <h3>Permission requirement</h3>
          <p>TODO: Add permission gate once role enforcement is centralized.</p>
        </article>
        <article className="module-card">
          <h3>Audit hook</h3>
          <p>TODO: Add audit log action for read/write events.</p>
        </article>
      </div>
    </section>
  );
}
REACT
fi

if [ ! -f "$CSS_FILE" ]; then
cat > "$CSS_FILE" <<CSS
.enterprise-module-shell {
  margin-top: 2rem;
  padding: 1.5rem;
  border: 1px solid var(--border-color, #d8dee9);
  border-radius: 1rem;
  background: var(--surface-color, #ffffff);
}

.module-header-row {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  align-items: flex-start;
}

.module-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 1rem;
  margin-top: 1rem;
}

.module-card {
  padding: 1rem;
  border: 1px solid var(--border-color, #d8dee9);
  border-radius: 0.75rem;
}

.dry-run-badge {
  padding: 0.35rem 0.75rem;
  border-radius: 999px;
  font-weight: 700;
  background: #eef6ff;
}
CSS
fi

if [ ! -f "$HELP_FILE" ]; then
cat > "$HELP_FILE" <<HELP
# ${MODULE_TITLE}

## Purpose

This Help Center article is a placeholder for the ${MODULE_TITLE} module.

## Demo Scope

- Frontend shell
- Backend endpoint placeholder
- Permission requirement placeholder
- Audit hook placeholder

## Production Follow-Up

- Complete role enforcement
- Complete audit events
- Complete export and reporting behavior
HELP
fi

echo "Created scaffold:"
echo "- $REACT_FILE"
echo "- $CSS_FILE"
echo "- $HELP_FILE"
